// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: recipe.proto
// Protobuf Java Version: 4.29.3

package recipe;

public final class RecipeOuterClass {
  private RecipeOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      RecipeOuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface IngredientOrBuilder extends
      // @@protoc_insertion_point(interface_extends:recipe.Ingredient)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>float amount = 1;</code>
     * @return The amount.
     */
    float getAmount();

    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>string unit = 3;</code>
     * @return The unit.
     */
    java.lang.String getUnit();
    /**
     * <code>string unit = 3;</code>
     * @return The bytes for unit.
     */
    com.google.protobuf.ByteString
        getUnitBytes();
  }
  /**
   * Protobuf type {@code recipe.Ingredient}
   */
  public static final class Ingredient extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:recipe.Ingredient)
      IngredientOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 3,
        /* suffix= */ "",
        Ingredient.class.getName());
    }
    // Use Ingredient.newBuilder() to construct.
    private Ingredient(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Ingredient() {
      name_ = "";
      unit_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return recipe.RecipeOuterClass.internal_static_recipe_Ingredient_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return recipe.RecipeOuterClass.internal_static_recipe_Ingredient_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              recipe.RecipeOuterClass.Ingredient.class, recipe.RecipeOuterClass.Ingredient.Builder.class);
    }

    public static final int AMOUNT_FIELD_NUMBER = 1;
    private float amount_ = 0F;
    /**
     * <code>float amount = 1;</code>
     * @return The amount.
     */
    @java.lang.Override
    public float getAmount() {
      return amount_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object name_ = "";
    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int UNIT_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object unit_ = "";
    /**
     * <code>string unit = 3;</code>
     * @return The unit.
     */
    @java.lang.Override
    public java.lang.String getUnit() {
      java.lang.Object ref = unit_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        unit_ = s;
        return s;
      }
    }
    /**
     * <code>string unit = 3;</code>
     * @return The bytes for unit.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUnitBytes() {
      java.lang.Object ref = unit_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        unit_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (java.lang.Float.floatToRawIntBits(amount_) != 0) {
        output.writeFloat(1, amount_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, name_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(unit_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, unit_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (java.lang.Float.floatToRawIntBits(amount_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(1, amount_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, name_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(unit_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, unit_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof recipe.RecipeOuterClass.Ingredient)) {
        return super.equals(obj);
      }
      recipe.RecipeOuterClass.Ingredient other = (recipe.RecipeOuterClass.Ingredient) obj;

      if (java.lang.Float.floatToIntBits(getAmount())
          != java.lang.Float.floatToIntBits(
              other.getAmount())) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (!getUnit()
          .equals(other.getUnit())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + AMOUNT_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getAmount());
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + UNIT_FIELD_NUMBER;
      hash = (53 * hash) + getUnit().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static recipe.RecipeOuterClass.Ingredient parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static recipe.RecipeOuterClass.Ingredient parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static recipe.RecipeOuterClass.Ingredient parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static recipe.RecipeOuterClass.Ingredient parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static recipe.RecipeOuterClass.Ingredient parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static recipe.RecipeOuterClass.Ingredient parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static recipe.RecipeOuterClass.Ingredient parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static recipe.RecipeOuterClass.Ingredient parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static recipe.RecipeOuterClass.Ingredient parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static recipe.RecipeOuterClass.Ingredient parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static recipe.RecipeOuterClass.Ingredient parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static recipe.RecipeOuterClass.Ingredient parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(recipe.RecipeOuterClass.Ingredient prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code recipe.Ingredient}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:recipe.Ingredient)
        recipe.RecipeOuterClass.IngredientOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return recipe.RecipeOuterClass.internal_static_recipe_Ingredient_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return recipe.RecipeOuterClass.internal_static_recipe_Ingredient_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                recipe.RecipeOuterClass.Ingredient.class, recipe.RecipeOuterClass.Ingredient.Builder.class);
      }

      // Construct using recipe.RecipeOuterClass.Ingredient.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        amount_ = 0F;
        name_ = "";
        unit_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return recipe.RecipeOuterClass.internal_static_recipe_Ingredient_descriptor;
      }

      @java.lang.Override
      public recipe.RecipeOuterClass.Ingredient getDefaultInstanceForType() {
        return recipe.RecipeOuterClass.Ingredient.getDefaultInstance();
      }

      @java.lang.Override
      public recipe.RecipeOuterClass.Ingredient build() {
        recipe.RecipeOuterClass.Ingredient result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public recipe.RecipeOuterClass.Ingredient buildPartial() {
        recipe.RecipeOuterClass.Ingredient result = new recipe.RecipeOuterClass.Ingredient(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(recipe.RecipeOuterClass.Ingredient result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.amount_ = amount_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.name_ = name_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.unit_ = unit_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof recipe.RecipeOuterClass.Ingredient) {
          return mergeFrom((recipe.RecipeOuterClass.Ingredient)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(recipe.RecipeOuterClass.Ingredient other) {
        if (other == recipe.RecipeOuterClass.Ingredient.getDefaultInstance()) return this;
        if (other.getAmount() != 0F) {
          setAmount(other.getAmount());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.getUnit().isEmpty()) {
          unit_ = other.unit_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 13: {
                amount_ = input.readFloat();
                bitField0_ |= 0x00000001;
                break;
              } // case 13
              case 18: {
                name_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                unit_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private float amount_ ;
      /**
       * <code>float amount = 1;</code>
       * @return The amount.
       */
      @java.lang.Override
      public float getAmount() {
        return amount_;
      }
      /**
       * <code>float amount = 1;</code>
       * @param value The amount to set.
       * @return This builder for chaining.
       */
      public Builder setAmount(float value) {

        amount_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>float amount = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearAmount() {
        bitField0_ = (bitField0_ & ~0x00000001);
        amount_ = 0F;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 2;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        name_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        name_ = getDefaultInstance().getName();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        name_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object unit_ = "";
      /**
       * <code>string unit = 3;</code>
       * @return The unit.
       */
      public java.lang.String getUnit() {
        java.lang.Object ref = unit_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          unit_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string unit = 3;</code>
       * @return The bytes for unit.
       */
      public com.google.protobuf.ByteString
          getUnitBytes() {
        java.lang.Object ref = unit_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          unit_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string unit = 3;</code>
       * @param value The unit to set.
       * @return This builder for chaining.
       */
      public Builder setUnit(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        unit_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string unit = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearUnit() {
        unit_ = getDefaultInstance().getUnit();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string unit = 3;</code>
       * @param value The bytes for unit to set.
       * @return This builder for chaining.
       */
      public Builder setUnitBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        unit_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:recipe.Ingredient)
    }

    // @@protoc_insertion_point(class_scope:recipe.Ingredient)
    private static final recipe.RecipeOuterClass.Ingredient DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new recipe.RecipeOuterClass.Ingredient();
    }

    public static recipe.RecipeOuterClass.Ingredient getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Ingredient>
        PARSER = new com.google.protobuf.AbstractParser<Ingredient>() {
      @java.lang.Override
      public Ingredient parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Ingredient> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Ingredient> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public recipe.RecipeOuterClass.Ingredient getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface RecipeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:recipe.Recipe)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint32 portions = 1;</code>
     * @return The portions.
     */
    int getPortions();

    /**
     * <code>uint32 active_time = 2;</code>
     * @return The activeTime.
     */
    int getActiveTime();

    /**
     * <code>uint32 passive_time = 3;</code>
     * @return The passiveTime.
     */
    int getPassiveTime();

    /**
     * <code>repeated .recipe.Ingredient ingredients = 4;</code>
     */
    java.util.List<recipe.RecipeOuterClass.Ingredient> 
        getIngredientsList();
    /**
     * <code>repeated .recipe.Ingredient ingredients = 4;</code>
     */
    recipe.RecipeOuterClass.Ingredient getIngredients(int index);
    /**
     * <code>repeated .recipe.Ingredient ingredients = 4;</code>
     */
    int getIngredientsCount();
    /**
     * <code>repeated .recipe.Ingredient ingredients = 4;</code>
     */
    java.util.List<? extends recipe.RecipeOuterClass.IngredientOrBuilder> 
        getIngredientsOrBuilderList();
    /**
     * <code>repeated .recipe.Ingredient ingredients = 4;</code>
     */
    recipe.RecipeOuterClass.IngredientOrBuilder getIngredientsOrBuilder(
        int index);

    /**
     * <code>repeated string instructions = 5;</code>
     * @return A list containing the instructions.
     */
    java.util.List<java.lang.String>
        getInstructionsList();
    /**
     * <code>repeated string instructions = 5;</code>
     * @return The count of instructions.
     */
    int getInstructionsCount();
    /**
     * <code>repeated string instructions = 5;</code>
     * @param index The index of the element to return.
     * @return The instructions at the given index.
     */
    java.lang.String getInstructions(int index);
    /**
     * <code>repeated string instructions = 5;</code>
     * @param index The index of the value to return.
     * @return The bytes of the instructions at the given index.
     */
    com.google.protobuf.ByteString
        getInstructionsBytes(int index);
  }
  /**
   * Protobuf type {@code recipe.Recipe}
   */
  public static final class Recipe extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:recipe.Recipe)
      RecipeOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 3,
        /* suffix= */ "",
        Recipe.class.getName());
    }
    // Use Recipe.newBuilder() to construct.
    private Recipe(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Recipe() {
      ingredients_ = java.util.Collections.emptyList();
      instructions_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return recipe.RecipeOuterClass.internal_static_recipe_Recipe_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return recipe.RecipeOuterClass.internal_static_recipe_Recipe_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              recipe.RecipeOuterClass.Recipe.class, recipe.RecipeOuterClass.Recipe.Builder.class);
    }

    public static final int PORTIONS_FIELD_NUMBER = 1;
    private int portions_ = 0;
    /**
     * <code>uint32 portions = 1;</code>
     * @return The portions.
     */
    @java.lang.Override
    public int getPortions() {
      return portions_;
    }

    public static final int ACTIVE_TIME_FIELD_NUMBER = 2;
    private int activeTime_ = 0;
    /**
     * <code>uint32 active_time = 2;</code>
     * @return The activeTime.
     */
    @java.lang.Override
    public int getActiveTime() {
      return activeTime_;
    }

    public static final int PASSIVE_TIME_FIELD_NUMBER = 3;
    private int passiveTime_ = 0;
    /**
     * <code>uint32 passive_time = 3;</code>
     * @return The passiveTime.
     */
    @java.lang.Override
    public int getPassiveTime() {
      return passiveTime_;
    }

    public static final int INGREDIENTS_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private java.util.List<recipe.RecipeOuterClass.Ingredient> ingredients_;
    /**
     * <code>repeated .recipe.Ingredient ingredients = 4;</code>
     */
    @java.lang.Override
    public java.util.List<recipe.RecipeOuterClass.Ingredient> getIngredientsList() {
      return ingredients_;
    }
    /**
     * <code>repeated .recipe.Ingredient ingredients = 4;</code>
     */
    @java.lang.Override
    public java.util.List<? extends recipe.RecipeOuterClass.IngredientOrBuilder> 
        getIngredientsOrBuilderList() {
      return ingredients_;
    }
    /**
     * <code>repeated .recipe.Ingredient ingredients = 4;</code>
     */
    @java.lang.Override
    public int getIngredientsCount() {
      return ingredients_.size();
    }
    /**
     * <code>repeated .recipe.Ingredient ingredients = 4;</code>
     */
    @java.lang.Override
    public recipe.RecipeOuterClass.Ingredient getIngredients(int index) {
      return ingredients_.get(index);
    }
    /**
     * <code>repeated .recipe.Ingredient ingredients = 4;</code>
     */
    @java.lang.Override
    public recipe.RecipeOuterClass.IngredientOrBuilder getIngredientsOrBuilder(
        int index) {
      return ingredients_.get(index);
    }

    public static final int INSTRUCTIONS_FIELD_NUMBER = 5;
    @SuppressWarnings("serial")
    private com.google.protobuf.LazyStringArrayList instructions_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    /**
     * <code>repeated string instructions = 5;</code>
     * @return A list containing the instructions.
     */
    public com.google.protobuf.ProtocolStringList
        getInstructionsList() {
      return instructions_;
    }
    /**
     * <code>repeated string instructions = 5;</code>
     * @return The count of instructions.
     */
    public int getInstructionsCount() {
      return instructions_.size();
    }
    /**
     * <code>repeated string instructions = 5;</code>
     * @param index The index of the element to return.
     * @return The instructions at the given index.
     */
    public java.lang.String getInstructions(int index) {
      return instructions_.get(index);
    }
    /**
     * <code>repeated string instructions = 5;</code>
     * @param index The index of the value to return.
     * @return The bytes of the instructions at the given index.
     */
    public com.google.protobuf.ByteString
        getInstructionsBytes(int index) {
      return instructions_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (portions_ != 0) {
        output.writeUInt32(1, portions_);
      }
      if (activeTime_ != 0) {
        output.writeUInt32(2, activeTime_);
      }
      if (passiveTime_ != 0) {
        output.writeUInt32(3, passiveTime_);
      }
      for (int i = 0; i < ingredients_.size(); i++) {
        output.writeMessage(4, ingredients_.get(i));
      }
      for (int i = 0; i < instructions_.size(); i++) {
        com.google.protobuf.GeneratedMessage.writeString(output, 5, instructions_.getRaw(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (portions_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, portions_);
      }
      if (activeTime_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, activeTime_);
      }
      if (passiveTime_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, passiveTime_);
      }
      for (int i = 0; i < ingredients_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, ingredients_.get(i));
      }
      {
        int dataSize = 0;
        for (int i = 0; i < instructions_.size(); i++) {
          dataSize += computeStringSizeNoTag(instructions_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getInstructionsList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof recipe.RecipeOuterClass.Recipe)) {
        return super.equals(obj);
      }
      recipe.RecipeOuterClass.Recipe other = (recipe.RecipeOuterClass.Recipe) obj;

      if (getPortions()
          != other.getPortions()) return false;
      if (getActiveTime()
          != other.getActiveTime()) return false;
      if (getPassiveTime()
          != other.getPassiveTime()) return false;
      if (!getIngredientsList()
          .equals(other.getIngredientsList())) return false;
      if (!getInstructionsList()
          .equals(other.getInstructionsList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PORTIONS_FIELD_NUMBER;
      hash = (53 * hash) + getPortions();
      hash = (37 * hash) + ACTIVE_TIME_FIELD_NUMBER;
      hash = (53 * hash) + getActiveTime();
      hash = (37 * hash) + PASSIVE_TIME_FIELD_NUMBER;
      hash = (53 * hash) + getPassiveTime();
      if (getIngredientsCount() > 0) {
        hash = (37 * hash) + INGREDIENTS_FIELD_NUMBER;
        hash = (53 * hash) + getIngredientsList().hashCode();
      }
      if (getInstructionsCount() > 0) {
        hash = (37 * hash) + INSTRUCTIONS_FIELD_NUMBER;
        hash = (53 * hash) + getInstructionsList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static recipe.RecipeOuterClass.Recipe parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static recipe.RecipeOuterClass.Recipe parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static recipe.RecipeOuterClass.Recipe parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static recipe.RecipeOuterClass.Recipe parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static recipe.RecipeOuterClass.Recipe parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static recipe.RecipeOuterClass.Recipe parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static recipe.RecipeOuterClass.Recipe parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static recipe.RecipeOuterClass.Recipe parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static recipe.RecipeOuterClass.Recipe parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static recipe.RecipeOuterClass.Recipe parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static recipe.RecipeOuterClass.Recipe parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static recipe.RecipeOuterClass.Recipe parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(recipe.RecipeOuterClass.Recipe prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code recipe.Recipe}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:recipe.Recipe)
        recipe.RecipeOuterClass.RecipeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return recipe.RecipeOuterClass.internal_static_recipe_Recipe_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return recipe.RecipeOuterClass.internal_static_recipe_Recipe_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                recipe.RecipeOuterClass.Recipe.class, recipe.RecipeOuterClass.Recipe.Builder.class);
      }

      // Construct using recipe.RecipeOuterClass.Recipe.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        portions_ = 0;
        activeTime_ = 0;
        passiveTime_ = 0;
        if (ingredientsBuilder_ == null) {
          ingredients_ = java.util.Collections.emptyList();
        } else {
          ingredients_ = null;
          ingredientsBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        instructions_ =
            com.google.protobuf.LazyStringArrayList.emptyList();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return recipe.RecipeOuterClass.internal_static_recipe_Recipe_descriptor;
      }

      @java.lang.Override
      public recipe.RecipeOuterClass.Recipe getDefaultInstanceForType() {
        return recipe.RecipeOuterClass.Recipe.getDefaultInstance();
      }

      @java.lang.Override
      public recipe.RecipeOuterClass.Recipe build() {
        recipe.RecipeOuterClass.Recipe result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public recipe.RecipeOuterClass.Recipe buildPartial() {
        recipe.RecipeOuterClass.Recipe result = new recipe.RecipeOuterClass.Recipe(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(recipe.RecipeOuterClass.Recipe result) {
        if (ingredientsBuilder_ == null) {
          if (((bitField0_ & 0x00000008) != 0)) {
            ingredients_ = java.util.Collections.unmodifiableList(ingredients_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.ingredients_ = ingredients_;
        } else {
          result.ingredients_ = ingredientsBuilder_.build();
        }
      }

      private void buildPartial0(recipe.RecipeOuterClass.Recipe result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.portions_ = portions_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.activeTime_ = activeTime_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.passiveTime_ = passiveTime_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          instructions_.makeImmutable();
          result.instructions_ = instructions_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof recipe.RecipeOuterClass.Recipe) {
          return mergeFrom((recipe.RecipeOuterClass.Recipe)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(recipe.RecipeOuterClass.Recipe other) {
        if (other == recipe.RecipeOuterClass.Recipe.getDefaultInstance()) return this;
        if (other.getPortions() != 0) {
          setPortions(other.getPortions());
        }
        if (other.getActiveTime() != 0) {
          setActiveTime(other.getActiveTime());
        }
        if (other.getPassiveTime() != 0) {
          setPassiveTime(other.getPassiveTime());
        }
        if (ingredientsBuilder_ == null) {
          if (!other.ingredients_.isEmpty()) {
            if (ingredients_.isEmpty()) {
              ingredients_ = other.ingredients_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureIngredientsIsMutable();
              ingredients_.addAll(other.ingredients_);
            }
            onChanged();
          }
        } else {
          if (!other.ingredients_.isEmpty()) {
            if (ingredientsBuilder_.isEmpty()) {
              ingredientsBuilder_.dispose();
              ingredientsBuilder_ = null;
              ingredients_ = other.ingredients_;
              bitField0_ = (bitField0_ & ~0x00000008);
              ingredientsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getIngredientsFieldBuilder() : null;
            } else {
              ingredientsBuilder_.addAllMessages(other.ingredients_);
            }
          }
        }
        if (!other.instructions_.isEmpty()) {
          if (instructions_.isEmpty()) {
            instructions_ = other.instructions_;
            bitField0_ |= 0x00000010;
          } else {
            ensureInstructionsIsMutable();
            instructions_.addAll(other.instructions_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                portions_ = input.readUInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                activeTime_ = input.readUInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 24: {
                passiveTime_ = input.readUInt32();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 34: {
                recipe.RecipeOuterClass.Ingredient m =
                    input.readMessage(
                        recipe.RecipeOuterClass.Ingredient.parser(),
                        extensionRegistry);
                if (ingredientsBuilder_ == null) {
                  ensureIngredientsIsMutable();
                  ingredients_.add(m);
                } else {
                  ingredientsBuilder_.addMessage(m);
                }
                break;
              } // case 34
              case 42: {
                java.lang.String s = input.readStringRequireUtf8();
                ensureInstructionsIsMutable();
                instructions_.add(s);
                break;
              } // case 42
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int portions_ ;
      /**
       * <code>uint32 portions = 1;</code>
       * @return The portions.
       */
      @java.lang.Override
      public int getPortions() {
        return portions_;
      }
      /**
       * <code>uint32 portions = 1;</code>
       * @param value The portions to set.
       * @return This builder for chaining.
       */
      public Builder setPortions(int value) {

        portions_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 portions = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearPortions() {
        bitField0_ = (bitField0_ & ~0x00000001);
        portions_ = 0;
        onChanged();
        return this;
      }

      private int activeTime_ ;
      /**
       * <code>uint32 active_time = 2;</code>
       * @return The activeTime.
       */
      @java.lang.Override
      public int getActiveTime() {
        return activeTime_;
      }
      /**
       * <code>uint32 active_time = 2;</code>
       * @param value The activeTime to set.
       * @return This builder for chaining.
       */
      public Builder setActiveTime(int value) {

        activeTime_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 active_time = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearActiveTime() {
        bitField0_ = (bitField0_ & ~0x00000002);
        activeTime_ = 0;
        onChanged();
        return this;
      }

      private int passiveTime_ ;
      /**
       * <code>uint32 passive_time = 3;</code>
       * @return The passiveTime.
       */
      @java.lang.Override
      public int getPassiveTime() {
        return passiveTime_;
      }
      /**
       * <code>uint32 passive_time = 3;</code>
       * @param value The passiveTime to set.
       * @return This builder for chaining.
       */
      public Builder setPassiveTime(int value) {

        passiveTime_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 passive_time = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearPassiveTime() {
        bitField0_ = (bitField0_ & ~0x00000004);
        passiveTime_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<recipe.RecipeOuterClass.Ingredient> ingredients_ =
        java.util.Collections.emptyList();
      private void ensureIngredientsIsMutable() {
        if (!((bitField0_ & 0x00000008) != 0)) {
          ingredients_ = new java.util.ArrayList<recipe.RecipeOuterClass.Ingredient>(ingredients_);
          bitField0_ |= 0x00000008;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          recipe.RecipeOuterClass.Ingredient, recipe.RecipeOuterClass.Ingredient.Builder, recipe.RecipeOuterClass.IngredientOrBuilder> ingredientsBuilder_;

      /**
       * <code>repeated .recipe.Ingredient ingredients = 4;</code>
       */
      public java.util.List<recipe.RecipeOuterClass.Ingredient> getIngredientsList() {
        if (ingredientsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(ingredients_);
        } else {
          return ingredientsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .recipe.Ingredient ingredients = 4;</code>
       */
      public int getIngredientsCount() {
        if (ingredientsBuilder_ == null) {
          return ingredients_.size();
        } else {
          return ingredientsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .recipe.Ingredient ingredients = 4;</code>
       */
      public recipe.RecipeOuterClass.Ingredient getIngredients(int index) {
        if (ingredientsBuilder_ == null) {
          return ingredients_.get(index);
        } else {
          return ingredientsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .recipe.Ingredient ingredients = 4;</code>
       */
      public Builder setIngredients(
          int index, recipe.RecipeOuterClass.Ingredient value) {
        if (ingredientsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureIngredientsIsMutable();
          ingredients_.set(index, value);
          onChanged();
        } else {
          ingredientsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .recipe.Ingredient ingredients = 4;</code>
       */
      public Builder setIngredients(
          int index, recipe.RecipeOuterClass.Ingredient.Builder builderForValue) {
        if (ingredientsBuilder_ == null) {
          ensureIngredientsIsMutable();
          ingredients_.set(index, builderForValue.build());
          onChanged();
        } else {
          ingredientsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .recipe.Ingredient ingredients = 4;</code>
       */
      public Builder addIngredients(recipe.RecipeOuterClass.Ingredient value) {
        if (ingredientsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureIngredientsIsMutable();
          ingredients_.add(value);
          onChanged();
        } else {
          ingredientsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .recipe.Ingredient ingredients = 4;</code>
       */
      public Builder addIngredients(
          int index, recipe.RecipeOuterClass.Ingredient value) {
        if (ingredientsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureIngredientsIsMutable();
          ingredients_.add(index, value);
          onChanged();
        } else {
          ingredientsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .recipe.Ingredient ingredients = 4;</code>
       */
      public Builder addIngredients(
          recipe.RecipeOuterClass.Ingredient.Builder builderForValue) {
        if (ingredientsBuilder_ == null) {
          ensureIngredientsIsMutable();
          ingredients_.add(builderForValue.build());
          onChanged();
        } else {
          ingredientsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .recipe.Ingredient ingredients = 4;</code>
       */
      public Builder addIngredients(
          int index, recipe.RecipeOuterClass.Ingredient.Builder builderForValue) {
        if (ingredientsBuilder_ == null) {
          ensureIngredientsIsMutable();
          ingredients_.add(index, builderForValue.build());
          onChanged();
        } else {
          ingredientsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .recipe.Ingredient ingredients = 4;</code>
       */
      public Builder addAllIngredients(
          java.lang.Iterable<? extends recipe.RecipeOuterClass.Ingredient> values) {
        if (ingredientsBuilder_ == null) {
          ensureIngredientsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, ingredients_);
          onChanged();
        } else {
          ingredientsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .recipe.Ingredient ingredients = 4;</code>
       */
      public Builder clearIngredients() {
        if (ingredientsBuilder_ == null) {
          ingredients_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          ingredientsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .recipe.Ingredient ingredients = 4;</code>
       */
      public Builder removeIngredients(int index) {
        if (ingredientsBuilder_ == null) {
          ensureIngredientsIsMutable();
          ingredients_.remove(index);
          onChanged();
        } else {
          ingredientsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .recipe.Ingredient ingredients = 4;</code>
       */
      public recipe.RecipeOuterClass.Ingredient.Builder getIngredientsBuilder(
          int index) {
        return getIngredientsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .recipe.Ingredient ingredients = 4;</code>
       */
      public recipe.RecipeOuterClass.IngredientOrBuilder getIngredientsOrBuilder(
          int index) {
        if (ingredientsBuilder_ == null) {
          return ingredients_.get(index);  } else {
          return ingredientsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .recipe.Ingredient ingredients = 4;</code>
       */
      public java.util.List<? extends recipe.RecipeOuterClass.IngredientOrBuilder> 
           getIngredientsOrBuilderList() {
        if (ingredientsBuilder_ != null) {
          return ingredientsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(ingredients_);
        }
      }
      /**
       * <code>repeated .recipe.Ingredient ingredients = 4;</code>
       */
      public recipe.RecipeOuterClass.Ingredient.Builder addIngredientsBuilder() {
        return getIngredientsFieldBuilder().addBuilder(
            recipe.RecipeOuterClass.Ingredient.getDefaultInstance());
      }
      /**
       * <code>repeated .recipe.Ingredient ingredients = 4;</code>
       */
      public recipe.RecipeOuterClass.Ingredient.Builder addIngredientsBuilder(
          int index) {
        return getIngredientsFieldBuilder().addBuilder(
            index, recipe.RecipeOuterClass.Ingredient.getDefaultInstance());
      }
      /**
       * <code>repeated .recipe.Ingredient ingredients = 4;</code>
       */
      public java.util.List<recipe.RecipeOuterClass.Ingredient.Builder> 
           getIngredientsBuilderList() {
        return getIngredientsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          recipe.RecipeOuterClass.Ingredient, recipe.RecipeOuterClass.Ingredient.Builder, recipe.RecipeOuterClass.IngredientOrBuilder> 
          getIngredientsFieldBuilder() {
        if (ingredientsBuilder_ == null) {
          ingredientsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              recipe.RecipeOuterClass.Ingredient, recipe.RecipeOuterClass.Ingredient.Builder, recipe.RecipeOuterClass.IngredientOrBuilder>(
                  ingredients_,
                  ((bitField0_ & 0x00000008) != 0),
                  getParentForChildren(),
                  isClean());
          ingredients_ = null;
        }
        return ingredientsBuilder_;
      }

      private com.google.protobuf.LazyStringArrayList instructions_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      private void ensureInstructionsIsMutable() {
        if (!instructions_.isModifiable()) {
          instructions_ = new com.google.protobuf.LazyStringArrayList(instructions_);
        }
        bitField0_ |= 0x00000010;
      }
      /**
       * <code>repeated string instructions = 5;</code>
       * @return A list containing the instructions.
       */
      public com.google.protobuf.ProtocolStringList
          getInstructionsList() {
        instructions_.makeImmutable();
        return instructions_;
      }
      /**
       * <code>repeated string instructions = 5;</code>
       * @return The count of instructions.
       */
      public int getInstructionsCount() {
        return instructions_.size();
      }
      /**
       * <code>repeated string instructions = 5;</code>
       * @param index The index of the element to return.
       * @return The instructions at the given index.
       */
      public java.lang.String getInstructions(int index) {
        return instructions_.get(index);
      }
      /**
       * <code>repeated string instructions = 5;</code>
       * @param index The index of the value to return.
       * @return The bytes of the instructions at the given index.
       */
      public com.google.protobuf.ByteString
          getInstructionsBytes(int index) {
        return instructions_.getByteString(index);
      }
      /**
       * <code>repeated string instructions = 5;</code>
       * @param index The index to set the value at.
       * @param value The instructions to set.
       * @return This builder for chaining.
       */
      public Builder setInstructions(
          int index, java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureInstructionsIsMutable();
        instructions_.set(index, value);
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string instructions = 5;</code>
       * @param value The instructions to add.
       * @return This builder for chaining.
       */
      public Builder addInstructions(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureInstructionsIsMutable();
        instructions_.add(value);
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string instructions = 5;</code>
       * @param values The instructions to add.
       * @return This builder for chaining.
       */
      public Builder addAllInstructions(
          java.lang.Iterable<java.lang.String> values) {
        ensureInstructionsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, instructions_);
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string instructions = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearInstructions() {
        instructions_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string instructions = 5;</code>
       * @param value The bytes of the instructions to add.
       * @return This builder for chaining.
       */
      public Builder addInstructionsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        ensureInstructionsIsMutable();
        instructions_.add(value);
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:recipe.Recipe)
    }

    // @@protoc_insertion_point(class_scope:recipe.Recipe)
    private static final recipe.RecipeOuterClass.Recipe DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new recipe.RecipeOuterClass.Recipe();
    }

    public static recipe.RecipeOuterClass.Recipe getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Recipe>
        PARSER = new com.google.protobuf.AbstractParser<Recipe>() {
      @java.lang.Override
      public Recipe parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Recipe> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Recipe> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public recipe.RecipeOuterClass.Recipe getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_recipe_Ingredient_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_recipe_Ingredient_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_recipe_Recipe_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_recipe_Recipe_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014recipe.proto\022\006recipe\"8\n\nIngredient\022\016\n\006" +
      "amount\030\001 \001(\002\022\014\n\004name\030\002 \001(\t\022\014\n\004unit\030\003 \001(\t" +
      "\"\204\001\n\006Recipe\022\020\n\010portions\030\001 \001(\r\022\023\n\013active_" +
      "time\030\002 \001(\r\022\024\n\014passive_time\030\003 \001(\r\022\'\n\013ingr" +
      "edients\030\004 \003(\0132\022.recipe.Ingredient\022\024\n\014ins" +
      "tructions\030\005 \003(\tb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_recipe_Ingredient_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_recipe_Ingredient_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_recipe_Ingredient_descriptor,
        new java.lang.String[] { "Amount", "Name", "Unit", });
    internal_static_recipe_Recipe_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_recipe_Recipe_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_recipe_Recipe_descriptor,
        new java.lang.String[] { "Portions", "ActiveTime", "PassiveTime", "Ingredients", "Instructions", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
